-- 1  retrive all success full bookings
CREATE VIEW SUCCESSFUL_BOOKING AS
SELECT * FROM dbo.July$
WHERE Booking_Status='Success';
--retrive all success full bookings
SELECT * FROM SUCCESSFUL_BOOKING;

-- 2 FIND THE AVERAGE RIDE DISTANCE FOR EACH VEHICLE TYPE
CREATE VIEW RIDE_DISTANCE_FOR_EACH_VECHILE AS
SELECT
Vehicle_Type,
AVG(Ride_Distance) AS AVG_RIDE_DISTANCE
FROM dbo.July$
GROUP BY Vehicle_Type;
--FIND THE AVERAGE RIDE DISTANCE FOR EACH VEHICLE TYPE
SELECT * FROM RIDE_DISTANCE_FOR_EACH_VECHILE;

-- 3 GET THE TOTAL NUMBER OF CANCELED RIDES BY CUSTOMERS
CREATE VIEW CANCELED_RIDES_BY_CUSTOMER AS
SELECT COUNT(*) AS TOTALCANCELED_RIDE FROM DBO.July$
WHERE Booking_Status = 'Canceled by Customer';
--GET THE TOTAL NUMBER OF CANCELED RIDES BY CUSTOMERS
SELECT * FROM CANCELED_RIDES_BY_CUSTOMER;

-- 4 LIST THE TOP 5 CUSTOMERS WHO BOOOKED THE HIGHEST NUMBER OF RIDES;
CREATE VIEW TOP_5_CUSTOMERS AS
SELECT TOP 5
Customer_ID,
COUNT(Booking_ID) AS TOTAL_RIDES
FROM DBO.July$
GROUP BY Customer_ID
ORDER BY TOTAL_RIDES DESC
--LIST THE TOP 5 CUSTOMERS WHO BOOOKED THE HIGHEST NUMBER OF RIDES;
SELECT * FROM TOP_5_CUSTOMERS;

-- 5 GET THE NUMBER OF RIDES CANCELED BY DRIVERS DUE TO PERSONAL AND CAR RELATED  ISSUES;
CREATE VIEW RIDES_CANCELED_BY_DRIVERS_CAR_RELATED AS
SELECT COUNT(*) AS CANCELED_RIDE_DRIVER
FROM DBO.July$
WHERE Canceled_Rides_by_Driver = 'Personal & Car related issue'
--GET THE NUMBER OF RIDES CANCELED BY DRIVERS DUE TO PERSONAL AND CAR RELATED  ISSUES
SELECT * FROM RIDES_CANCELED_BY_DRIVERS_CAR_RELATED;

-- 6 FIND THE MAXIMUM AND MINIMUM DRIVER RATING FOR PRIME SADAN BOOKINGS;
CREATE VIEW max_min_driver_ratibg AS
SELECT
MAX(Driver_Ratings) AS MAXIMUM_DRIVER_RATING,
MIN(Driver_Ratings) AS MINIMUM_DRIVER_RATING
FROM DBO.July$
WHERE Vehicle_Type = 'Prime Sedan';
--FIND THE MAXIMUM AND MINIMUM DRIVER RATING FOR PRIME SADAN BOOKINGS;
SELECT * FROM max_min_driver_ratibg;

-- 7 RETRIVE ALL RIDES WHERE PAYMENT WAS MADE USING UPT
CREATE VIEW UPI_PAYMENT AS
SELECT * FROM DBO.July$
WHERE Payment_Method = 'UPI'
--RETRIVE ALL RIDES WHERE PAYMENT WAS MADE USING UPT
SELECT * FROM UPI_PAYMENT

-- 8 FIND THE AVERAGE CUSTOMER RATING PER VECHILE TYPE
CREATE VIEW AVERAGE_CUSTOMER_RATING_PER_VECHILE AS
SELECT 
AVG(Customer_Rating) AS AVERAGE_CUSTOMER_RATING,
Vehicle_Type
FROM DBO.July$
GROUP BY Vehicle_Type
--FIND THE AVERAGE CUSTOMER RATING PER VECHILE TYPE
SELECT * FROM AVERAGE_CUSTOMER_RATING_PER_VECHILE;

-- 9 CALCULATE THE TOTAL BOOKING VALUE OF RIDES COMPLETED SUCCESSFULLY
CREATE VIEW TOTAL_SUCCESSFUL_RIDE_VALUE AS
SELECT
SUM(Booking_Value) AS TOTAL_SUCCESSFUL_VALUE
FROM DBO.July$
WHERE Booking_Status = 'Success';
--CALCULATE THE TOTAL BOOKING VALUE OF RIDES COMPLETED SUCCESSFULLY
SELECT* FROM TOTAL_SUCCESSFUL_RIDE_VALUE;


-- 10 list all incomplete rides along with the reason
CREATE VIEW INCOMPLETE_RIDES_REASONS AS
SELECT
Booking_ID,
Incomplete_Rides_Reason
FROM DBO.July$
WHERE Incomplete_Rides = 'Yes';
--list all incomplete rides along with the reason
SELECT *FROM INCOMPLETE_RIDES_REASONS;
